error 1
    Your borrowed books:
Traceback (most recent call last):
  File "F:\Career\Projects\Python\Library-Management-System\Project\main.py", line 119, in <module>
    main()
  File "F:\Career\Projects\Python\Library-Management-System\Project\main.py", line 111, in main
    book = library.books[book_id]
KeyError: ''
PS F:\Career\Projects\Python\Library-Management-System\Project> 